version: '3'

services:
  postgres-dev:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "mod64"
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - /app/PostgreSQL:/var/lib/postgresql/data
    networks:
      - dev-network

  pgadmin-portal:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "mod64bits@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Mod64!"
    ports:
      - "8090:80"
    depends_on:
      - postgres-dev
    networks:
      - dev-network

networks:
  portal-network:
    external: true
    # driver: bridge
