# Generated by Django 4.1 on 2022-08-10 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0002_alter_patients_birth_date_alter_patients_ethnicity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modificado em"
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("Schedule_day", models.DateTimeField(verbose_name="Data")),
                (
                    "concluded",
                    models.BooleanField(default=False, verbose_name="Concluído"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_patient",
                        to="patients.patients",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
