# Generated by Django 4.1 on 2022-08-11 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="schedule", name="slug",),
    ]
