# Generated by Django 4.1 on 2022-08-09 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modificado em"
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                ("name", models.CharField(max_length=50, verbose_name="Nome")),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Patients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modificado em"
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=255, unique=True)),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Nome Completo"),
                ),
                (
                    "social_name",
                    models.CharField(max_length=100, verbose_name="Nome Social"),
                ),
                ("birth_date", models.DateField(verbose_name="data de Nascimento")),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("-", "-------"),
                            ("M", "Maculino"),
                            ("F", "Feminino"),
                            ("O", "Outro"),
                        ],
                        default="-",
                        max_length=1,
                        verbose_name="Gênero",
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        choices=[
                            ("-", "-------"),
                            ("I", "Indígena"),
                            ("N", "Negro"),
                            ("B", "Branco"),
                            ("P", "Pardo"),
                            ("O", "Outros"),
                        ],
                        default="-",
                        max_length=1,
                        verbose_name="Itenia",
                    ),
                ),
                ("cpf", models.CharField(max_length=20, verbose_name="CPF")),
                ("rg", models.CharField(max_length=20, verbose_name="RG")),
                (
                    "health_insurance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.healthinsurance",
                        verbose_name="Convênio",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
