# Generated by Django 4.1 on 2022-08-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patients",
            name="birth_date",
            field=models.DateField(verbose_name="Nascimento"),
        ),
        migrations.AlterField(
            model_name="patients",
            name="ethnicity",
            field=models.CharField(
                choices=[
                    ("-", "-------"),
                    ("I", "Indígena"),
                    ("N", "Negro"),
                    ("B", "Branco"),
                    ("P", "Pardo"),
                    ("O", "Outros"),
                ],
                default="-",
                max_length=1,
                verbose_name="Etnia",
            ),
        ),
    ]
